# Generated by Django 5.2.13 on 2026-04-09 08:02

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with this email already exists.'}, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with this username already exists.'}, max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=15, validators=[apps.common.validators.ZimbabwePhoneValidator()])),
                ('role', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator')], db_index=True, default='BUYER', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, default='', upload_to='profile_pictures/%Y/%m/', validators=[apps.common.validators.ImageSizeValidator(max_mb=5)])),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MUTARE', 'Mutare'), ('GWERU', 'Gweru'), ('KWEKWE', 'Kwekwe'), ('KADOMA', 'Kadoma'), ('MASVINGO', 'Masvingo'), ('CHINHOYI', 'Chinhoyi'), ('BINDURA', 'Bindura'), ('CHEGUTU', 'Chegutu'), ('MARONDERA', 'Marondera'), ('KAROI', 'Karoi'), ('VICTORIA_FALLS', 'Victoria Falls'), ('HWANGE', 'Hwange'), ('BEITBRIDGE', 'Beitbridge'), ('CHITUNGWIZA', 'Chitungwiza'), ('EPWORTH', 'Epworth'), ('NORTON', 'Norton'), ('RUWA', 'Ruwa'), ('ZVISHAVANE', 'Zvishavane'), ('CHIREDZI', 'Chiredzi'), ('CHIPINGE', 'Chipinge'), ('RUSAPE', 'Rusape'), ('PLUMTREE', 'Plumtree'), ('GWANDA', 'Gwanda'), ('SHURUGWI', 'Shurugwi'), ('REDCLIFF', 'Redcliff'), ('KARIBA', 'Kariba'), ('NYANGA', 'Nyanga'), ('MVURWI', 'Mvurwi'), ('GOKWE', 'Gokwe'), ('LUPANE', 'Lupane'), ('TRIANGLE', 'Triangle'), ('PENHALONGA', 'Penhalonga'), ('OTHER', 'Other')], default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
