# Generated by Django 5.2.13 on 2026-04-09 08:02

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text="Icon name or emoji (e.g. '📱', 'car', 'home').", max_length=50)),
                ('image', models.ImageField(blank=True, default='', upload_to='category_images/%Y/%m/', validators=[apps.common.validators.ImageSizeValidator(max_mb=5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='idx_cat_parent_active')],
            },
        ),
    ]
