# Generated by Django 5.2.13 on 2026-04-09 08:45

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwe Dollar')], default='USD', max_length=5)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('location', models.CharField(choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MUTARE', 'Mutare'), ('GWERU', 'Gweru'), ('KWEKWE', 'Kwekwe'), ('KADOMA', 'Kadoma'), ('MASVINGO', 'Masvingo'), ('CHINHOYI', 'Chinhoyi'), ('BINDURA', 'Bindura'), ('CHEGUTU', 'Chegutu'), ('MARONDERA', 'Marondera'), ('KAROI', 'Karoi'), ('VICTORIA_FALLS', 'Victoria Falls'), ('HWANGE', 'Hwange'), ('BEITBRIDGE', 'Beitbridge'), ('CHITUNGWIZA', 'Chitungwiza'), ('EPWORTH', 'Epworth'), ('NORTON', 'Norton'), ('RUWA', 'Ruwa'), ('ZVISHAVANE', 'Zvishavane'), ('CHIREDZI', 'Chiredzi'), ('CHIPINGE', 'Chipinge'), ('RUSAPE', 'Rusape'), ('PLUMTREE', 'Plumtree'), ('GWANDA', 'Gwanda'), ('SHURUGWI', 'Shurugwi'), ('REDCLIFF', 'Redcliff'), ('KARIBA', 'Kariba'), ('NYANGA', 'Nyanga'), ('MVURWI', 'Mvurwi'), ('GOKWE', 'Gokwe'), ('LUPANE', 'Lupane'), ('TRIANGLE', 'Triangle'), ('PENHALONGA', 'Penhalonga'), ('OTHER', 'Other')], max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/%Y/%m/', validators=[apps.common.validators.ImageSizeValidator(max_mb=5), apps.common.validators.ImageContentTypeValidator(allowed=['image/jpeg', 'image/png', 'image/webp'])])),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='idx_listing_status_created'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='idx_listing_cat_status'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner', 'status'], name='idx_listing_owner_status'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location', 'status'], name='idx_listing_loc_status'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured', 'status'], name='idx_listing_feat_status'),
        ),
    ]
